INSERT INTO user (username, password, createdAt) VALUES
  ('test1', '$2a$10$frsDN/01GTFr.VGeTFzd.O2D8K8NttulX75OCOae0ZjFKoykDRezS', now()),
  ('test2', '$2a$10$AKrPUae0A8JkTJALVua.9ulbLV8zA5Geiy/9IwTZrvsRy3OgaSsa2', now()),
  ('test3', '$2a$10$vKexrbYM/N7YMuaR4xElBOcLzZB5KM/RMS8.JPSDPwW.9LqDBF0ka', now()),
  ('test4', '$2a$10$TqF.17ExC9kKmLqQ3ScumOjgD81eF2c7POfPViZYGUXtJTxqiVDm2', now()),
  ('test5', '$2a$10$8UTm.UEi2Zs0Eq8WyhBq0.uYguc9Rg.bm5/4nVW8J4hRjWJZuruH6', now());


INSERT INTO board (username, title, post, createdAt, modifiedAt) VALUES
  ('test1', 'title1', 'post1', now(), now()),
  ('test2', 'title2', 'post2', now(), now()),
  ('test4', 'title3', 'post3', now(), now()),
  ('test5', 'title4', 'post4', now(), now()),
  ('test3', 'title5', 'post5', now(), now()),
  ('test1', 'title6', 'post6', now(), now()),
  ('test4', 'title7', 'post7', now(), now()),
  ('test2', 'title8', 'post8', now(), now()),
  ('test3', 'title9', 'post9', now(), now()),
  ('test4', 'title10', 'post10', now(), now()),
  ('test5', 'title11', 'post11', now(), now()),
  ('test2', 'title12', 'post12', now(), now()),
  ('test3', 'title13', 'post13', now(), now()),
  ('test1', 'title14', 'post14', now(), now()),
  ('test1', 'title15', 'post15', now(), now()),
  ('test4', 'title16', 'post16', now(), now()),
  ('test2', 'title17', 'post17', now(), now()),
  ('test2', 'title18', 'post18', now(), now()),
  ('test5', 'title19', 'post19', now(), now()),
  ('test2', 'title20', 'post20', now(), now()),
  ('test3', 'title21', 'post21', now(), now()),
  ('test1', 'title22', 'post22', now(), now()),
  ('test4', 'title23', 'post23', now(), now()),
  ('test3', 'title24', 'post24', now(), now()),
  ('test2', 'title25', 'post25', now(), now()),
  ('test1', 'title26', 'post26', now(), now()),
  ('test4', 'title27', 'post27', now(), now()),
  ('test2', 'title28', 'post28', now(), now()),
  ('test3', 'title29', 'post29', now(), now()),
  ('test2', 'title30', 'post30', now(), now()),
  ('test4', 'title31', 'post31', now(), now()),
  ('test2', 'title32', 'post32', now(), now()),
  ('test1', 'title33', 'post33', now(), now()),
  ('test5', 'title34', 'post34', now(), now()),
  ('test2', 'title35', 'post35', now(), now()),
  ('test2', 'title36', 'post36', now(), now()),
  ('test1', 'title37', 'post37', now(), now()),
  ('test3', 'title38', 'post38', now(), now()),
  ('test4', 'title39', 'post39', now(), now()),
  ('test2', 'title40', 'post40', now(), now()),
  ('test1', 'title41', 'post41', now(), now()),
  ('test5', 'title42', 'post42', now(), now());
  

